name: mini
channels:
  - defaults
  - conda-forge
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_1
  - entrypoints=0.3=py38_0
  - flake8=3.7.9=py38_0
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2020.0=166
  - mccabe=0.6.1=py38_1
  - mkl=2020.0=166
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.0.15=py38h14836fe_0
  - mkl_random=1.1.0=py38hf9181ef_0
  - mypy=0.750=py_0
  - mypy_extensions=0.4.3=py38_0
  - numpy=1.18.1=py38h93ca92e_0
  - numpy-base=1.18.1=py38hc3f5095_1
  - openssl=1.1.1e=he774522_0
  - pip=20.0.2=py38_1
  - psutil=5.7.0=py38he774522_0
  - pycodestyle=2.5.0=py38_0
  - pyflakes=2.1.1=py38_0
  - python=3.8.2=h5fd99cc_0
  - scipy=1.4.1=py38h9439919_0
  - setuptools=46.1.3=py38_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=he774522_0
  - typed-ast=1.4.1=py38he774522_0
  - typing_extensions=3.7.4.1=py38_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wheel=0.34.2=py38_0
  - wincertstore=0.2=py38_0
prefix: C:\Users\dfulford\miniconda3\envs\mini

